# This file was generated by GoReleaser. DO NOT EDIT.
cask "acdc-mcp" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "d8b2897dc68d3a14f5490bb55bc46fb32e82c9e624688931410ec73a6ee6c3a9"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d5b04030c4ca17f1d6aeb729f87d9c5ca2435b4146ef2ac07f80cc68e132776"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e59b5076d8fb04c09586ecdcf08ee00ddd6f3d6dd0fec153dd03d2b59e0d5db"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4891fc2ba60bc422e0affb8cf98f21f05e86e0b4b71bbeaa4a47a8dfafbdb4e"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_x86_64.tar.gz"
    end
  end

  name "acdc-mcp"
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acdc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acdc-mcp"]
    end
  end

  # No zap stanza required
end
