# This file was generated by GoReleaser. DO NOT EDIT.
cask "acdc-mcp" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "e628ad8918dfb380b99d17db47d8d3ea28ce739dc04e5f36fec97127646d4550"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e33cdad43a3ac38a63b59c333f58f7ec1f7c2e80c85052c4f2d6f0572b711e1d"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25fa93df9d504fadf09de273b204122161228a6bb1499cda5570163bb7d29388"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4a63ab6fea5097980da1bc2e4dbd5fad3656d7e267e84868786b70903a0d6d62"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_arm64.tar.gz"
    end
  end

  name "acdc-mcp"
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acdc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acdc-mcp"]
    end
  end

  # No zap stanza required

end
