# This file was generated by GoReleaser. DO NOT EDIT.
cask "acdc-mcp" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "263f680ad13fbc8f4f1a4ac251b8114f6a559b18be4ff8ec1b2bb3fea317c5ad"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c35027c27be03000a0fd4af9161a13ade507b3219f171f314104fdb2f904e11f"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6234a156c2f07741b2ba9ead761363875f2b2e670b44fb44586105073eb9b2d8"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a2ecc1484fc04a30fe0358da17ce6a7ea4db0494ae60a9a059249db3e974b647"
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_arm64.tar.gz"
    end
  end

  name "acdc-mcp"
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acdc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acdc-mcp"]
    end
  end

  # No zap stanza required

end
