# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-acdc-server" do
  name "mcp-acdc-server"
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-acdc-server"

  on_macos do
    on_intel do
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_x86_64.tar.gz"
      sha256 "ab1aec231d9434230c2876e59183aa21aa21710e5b46f830990c21bcadffc592"
    end
    on_arm do
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Darwin_arm64.tar.gz"
      sha256 "557934e8c9525006c2e0fabb5fd20a68bd4e07c2996e2de8bd24a7e725bac181"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_x86_64.tar.gz"
      sha256 "b5867700f1693781e6876b0e3e859753ad454bc77af644489d924c0b414a6cd2"
    end
    on_arm do
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v#{version}/mcp-acdc-server_Linux_arm64.tar.gz"
      sha256 "4a2459f9e16382054be61e6002df66d44fd15e41eacee7cc829080906abc28a4"
    end
  end

  # No zap stanza required
end
