# This file was generated by GoReleaser. DO NOT EDIT.
cask "projmark" do
  name "projmark"
  desc "CLI tool for tagging macOS directories with Finder tags based on project type"
  homepage "https://github.com/sha1n/project-marker"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projmark"

  on_macos do
    on_intel do
      url "https://github.com/sha1n/project-marker/releases/download/v#{version}/project-marker_Darwin_x86_64.tar.gz"
      sha256 "50ea34706ae9404635d33c40015a1dcfd99baf19f6b45c55c373e2e4e3264b7a"
    end
    on_arm do
      url "https://github.com/sha1n/project-marker/releases/download/v#{version}/project-marker_Darwin_arm64.tar.gz"
      sha256 "1b2c7018f33342e198b3c9827240f1e3058fa890c287657813dfaae3cd6d99f8"
    end
  end

  # No zap stanza required
end
