# This file was generated by GoReleaser. DO NOT EDIT.
cask "projmark" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "7c76f5b14e34b665b111530989e913ab41a151829ea85e85c6868234027851c1"
      url "https://github.com/sha1n/project-marker/releases/download/v#{version}/project-marker_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35393166c6670cbcd5ddc67677d94599b0a949925a9134ffa869f506292bcbde"
      url "https://github.com/sha1n/project-marker/releases/download/v#{version}/project-marker_Darwin_x86_64.tar.gz"
    end
  end

  name "projmark"
  desc "CLI tool for tagging macOS directories with Finder tags based on project type"
  homepage "https://github.com/sha1n/project-marker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projmark"

  # No zap stanza required
end
