# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcdcMcp < Formula
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.4.0/mcp-acdc-server_Darwin_x86_64.tar.gz"
      sha256 "921ea0e03b50cc8a40fc03be7b0ccd111cc968386ab1036e2f3a28b6c50f3ee6"

      def install
        bin.install "acdc-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.4.0/mcp-acdc-server_Darwin_arm64.tar.gz"
      sha256 "e0659cc885a256a796f1be3ee17c8013b47e9fb51e68881cf4be52db918753f2"

      def install
        bin.install "acdc-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.4.0/mcp-acdc-server_Linux_x86_64.tar.gz"
      sha256 "e0e9b4e5cb48669593040de915624fcd8fe4796b387102a01a935c9de555d8a9"
      def install
        bin.install "acdc-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.4.0/mcp-acdc-server_Linux_arm64.tar.gz"
      sha256 "b3b061cadf5c5280dd2c8dff35656a83d8db84cb87e02d2f76d0d1b4c7be6fcd"
      def install
        bin.install "acdc-mcp"
      end
    end
  end
end
