# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bert < Formula
  desc "CLI benchmarking tool"
  homepage "https://sha1n.github.io/bert/"
  version "2.3.10"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/bert/releases/download/v2.3.10/bert_2.3.10_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "72dd4f0ac8df41ea76665f94e58d10228f18099cc07850fabc9dc32449bf6153"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sha1n/bert/releases/download/v2.3.10/bert_2.3.10_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "aac21b870ff8ad2816e24ccb753b7ac36bdadbd0bb25fd3f600b2d32c4f2c71a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/bert/releases/download/v2.3.10/bert_2.3.10_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e1b78a42e091736e105e702f01ef09bfd1309fc159fe29c2a6034daa31b3ed02"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/bert/releases/download/v2.3.10/bert_2.3.10_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "3e4b686ff282f2c7f97e0befd47e2b28c0b79560e8cf4aad54353b66331208ed"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/bert/releases/download/v2.3.10/bert_2.3.10_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4c710afb8b45d1d5524f0f9eb2c1d21bd553c1782cf47e254aca899ad3ddead9"
    end
  end

  def install
    bin.install "bert"
  end

  test do
    system "#{bin}/bert --version"
  end
end
