# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bert < Formula
  desc "CLI benchmarking tool"
  homepage "https://sha1n.github.io/bert/"
  version "2.3.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/bert/releases/download/v2.3.18/bert_2.3.18_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8fc2a9d75eb3bb7392541e28f5bf5bc244b99cf901368a4fbd064d8bf11490ff"

      def install
        bin.install "bert"
        bash_completion.install "completions/bert.bash" => "bert"
        fish_completion.install "completions/bert.fish" => "bert"
        zsh_completion.install "completions/_bert" => "_bert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sha1n/bert/releases/download/v2.3.18/bert_2.3.18_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "494f59ef1050291d27231153078b7ab328b668617d1006494ce575f5c01bd89a"

      def install
        bin.install "bert"
        bash_completion.install "completions/bert.bash" => "bert"
        fish_completion.install "completions/bert.fish" => "bert"
        zsh_completion.install "completions/_bert" => "_bert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/bert/releases/download/v2.3.18/bert_2.3.18_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "fa199d8158b6eefe63322c9e753f0003b135a07a19cdfe498a592eed61397dc5"

      def install
        bin.install "bert"
        bash_completion.install "completions/bert.bash" => "bert"
        fish_completion.install "completions/bert.fish" => "bert"
        zsh_completion.install "completions/_bert" => "_bert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/bert/releases/download/v2.3.18/bert_2.3.18_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b39733991121c273c54d85d22ebc4e808bf4dee5a1b9f1840d7a9d899b10bb1d"

      def install
        bin.install "bert"
        bash_completion.install "completions/bert.bash" => "bert"
        fish_completion.install "completions/bert.fish" => "bert"
        zsh_completion.install "completions/_bert" => "_bert"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/bert/releases/download/v2.3.18/bert_2.3.18_Linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "72f1a6272dbdfe4899e9d9f5e54cbd5de7a3e09fc1f101656e7a2160be81fb0a"

      def install
        bin.install "bert"
        bash_completion.install "completions/bert.bash" => "bert"
        fish_completion.install "completions/bert.fish" => "bert"
        zsh_completion.install "completions/_bert" => "_bert"
      end
    end
  end

  test do
    system "#{bin}/bert --version"
  end
end
