# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hako < Formula
  desc "A multi-platform echo HTTP server utility with a simple CLI interface"
  homepage "https://sha1n.github.io/hako/"
  version "0.6.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/hako/releases/download/v0.6.12/hako_0.6.12_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "85e157def4cd1de9d64e63f3fea66a280373558db379808ed305f94420426c5e"

      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sha1n/hako/releases/download/v0.6.12/hako_0.6.12_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "316b54ba0987c379c945e27b220e031549cdf15a446ec571ac2ee67a820a8aa7"

      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/hako/releases/download/v0.6.12/hako_0.6.12_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "12d5a89d18a20f97a9d92b926a0c9fc2c13f3e30f07c680403fde901746862cc"
      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/hako/releases/download/v0.6.12/hako_0.6.12_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "031b342d3630917fc468513429e28ee5ab052bc472d470d920f2fc85ace2170a"
      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/hako/releases/download/v0.6.12/hako_0.6.12_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab0a6fc60d178a82ca1c604ccf1880e7d8eb14acc3c7b9dfec0aae491113eb7e"
      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
  end

  test do
    system "#{bin}/hako --version"
  end
end
