# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hako < Formula
  desc "CLI benchmarking tool"
  homepage "https://sha1n.github.io/hako/"
  version "0.6.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sha1n/hako/releases/download/v0.6.11/hako_0.6.11_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "455cef288a32cfaa38fcc0f6df74dbcbd5bea7bce803867750dfbf188af63240"

      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
    on_arm do
      url "https://github.com/sha1n/hako/releases/download/v0.6.11/hako_0.6.11_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5a009da86ab4471c34ea41af5472175283cfe0696e0c847b60d7fdddd8c80f38"

      def install
        bin.install "hako"
        bash_completion.install "completions/hako.bash" => "hako"
        fish_completion.install "completions/hako.fish" => "hako"
        zsh_completion.install "completions/_hako" => "_hako"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sha1n/hako/releases/download/v0.6.11/hako_0.6.11_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "627bb66d51a826ce6b18b9981fbc254162ceaa7806439317247a9f05892643c0"

        def install
          bin.install "hako"
          bash_completion.install "completions/hako.bash" => "hako"
          fish_completion.install "completions/hako.fish" => "hako"
          zsh_completion.install "completions/_hako" => "_hako"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sha1n/hako/releases/download/v0.6.11/hako_0.6.11_linux_armv6.tar.gz", using: CurlDownloadStrategy
        sha256 "e8644c6fff55fa10da349cdfd4d70853c4e2b22775b5cf171b60a91f60c0d735"

        def install
          bin.install "hako"
          bash_completion.install "completions/hako.bash" => "hako"
          fish_completion.install "completions/hako.fish" => "hako"
          zsh_completion.install "completions/_hako" => "_hako"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sha1n/hako/releases/download/v0.6.11/hako_0.6.11_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "49d8ad8d913100a0ec8fa49a91576736361fa4c9d20c24a18434e83e8ad08a9e"

        def install
          bin.install "hako"
          bash_completion.install "completions/hako.bash" => "hako"
          fish_completion.install "completions/hako.fish" => "hako"
          zsh_completion.install "completions/_hako" => "_hako"
        end
      end
    end
  end

  test do
    system "#{bin}/hako --version"
  end
end
