# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpAcdcServer < Formula
  desc "MCP ACDC Server"
  homepage "https://github.com/sha1n/mcp-acdc-server"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.1.1/mcp-acdc-server_Darwin_x86_64.tar.gz"
      sha256 "eb1cd9cf46b6f3c736064bd06531fd9db3e93f01ffcea190208471d48532df4e"

      def install
        bin.install "acdc-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.1.1/mcp-acdc-server_Darwin_arm64.tar.gz"
      sha256 "068fd26f24d69609cadbc005efac175a0e07165b592f9fe227a14f85274286b0"

      def install
        bin.install "acdc-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.1.1/mcp-acdc-server_Linux_x86_64.tar.gz"
      sha256 "4191e4b1bcb164671d868684ce409e5cda443fb140e4c8e08fa58e18735503fd"
      def install
        bin.install "acdc-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sha1n/mcp-acdc-server/releases/download/v0.1.1/mcp-acdc-server_Linux_arm64.tar.gz"
      sha256 "081ac0b7fdbea34d85da40c7d66883ef133ca3cab153490d111a875d8709076f"
      def install
        bin.install "acdc-mcp"
      end
    end
  end
end
